name: Auto Generate SEO-Optimized HTML Articles and Update Index Page

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main

jobs:
  generate_html_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: curl

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Generate Detailed SEO-Optimized HTML Files
      run: |
        # Function to generate detailed SEO articles using Cohere AI
        generate_html() {
          curl --request POST \
            --url https://api.cohere.com/v1/chat \
            --header 'accept: application/json' \
            --header 'content-type: application/json' \
            --header "Authorization: bearer brAX2r8rdDQaFxpx0u2PjWOXd8LKO8n9b1MNB0BQ" \
            --data '{
            "message": "Write a detailed, long-form SEO-optimized article with multiple sections, headings, paragraphs, and backlinks, fully valid HTML structure, including all necessary meta tags, Open Graph tags, and schema.org data, for flashusdtsender.xyz. The article should cover SEO best practices and link to relevant domains.",
            "model": "command-r-plus",
            "preamble": "You are an AI expert. Your task is to generate SEO-friendly, high-quality, structured articles with proper HTML formatting."
          }' | jq -r '.message' > article.html
        }

        # Create 10 SEO-optimized HTML files
        for i in $(seq 1 10); do
          echo "Generating SEO Article $i"
          generate_html
          mv article.html "articles/randomnumber$i.html"
          echo "Article $i created: randomnumber$i.html"
        done

    - name: Generate Index Page
      run: |
        # Generate the root index.html file
        echo "<!DOCTYPE html> ... (same index.html content here) ..." > index.html

    - name: Commit and push generated files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add index.html articles/
        git commit -m "Generated new SEO-optimized HTML articles and updated index page"
        git push origin main
